config/routes.rb
Einarlove::Application.routes.draw do

	# Root
	match "/" => redirect("/portfolio")

	#Admin
	get '/admin' => "admin#index"
	get '/login' => "admin#login"
	post '/login' => "admin#login"
	get '/logout' => "admin#logout"

	#Articles
	resources :articles, path: 'article'
	match '/article' => redirect('/articles')
	match '/blog' => redirect('/articles')
	match '/articles' => 'articles#index'
	match '/articles/about/:topic' => 'articles#about'
	get '/article/:id/:name.:extension' => 'articles#image'

	#Pages
	resources :pages
	get '/:id' => 'pages#show'
	get '/pages/:id/delete' => "pages#destroy"

	#Portfolio
	resources :portfolio_items
	get '/portfolio/:id' => 'portfolio_items#show'

	#Contact form
	post '/contact' => 'pages#mail'

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :title, :author, :content, :content_html, :topic, :published, :slug
  has_many :images

  before_save :generate_html

  extend FriendlyId
  friendly_id :title, use: :slugged

  protected

  def generate_html
    return if content.blank?
    markdown = Redcarpet::Markdown.new(
      Redcarpet::Render::HTML.new(),
      no_intra_emphasis: true,
      autolink: true,
      fenced_code_blocks:true,
      strikethrough: true)

    self.content_html = Redcarpet::Render::SmartyPants.render(
      markdown.render(content))
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :name, :title, :credit, :caption, :extension, :url
  belongs_to :article
end

app/models/message.rb
class Message

	include ActiveModel::Validations
	include ActiveModel::Conversion
	extend ActiveModel::Naming

	attr_accessor :name, :email, :subject, :body

	validates :name, :email, :body, :presence => true
	validates :email, :format => { :with => %r{.+@.+\..+} }
	validates :body, length: {minimum: 50, message: "is quite short isn't it?"}
	
	def initialize(attributes = {})
		attributes.each do |name, value|
			send("#{name}=", value)
		end
	end

	def persisted?
		false
	end

end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :body, :image, :name, :title, :layout, :visible, :slug, :description

  validates :name,   presence: true
	validates :layout, presence: true
  validates :slug,   presence: true, uniqueness: true

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/portfolio_item.rb
class PortfolioItem < ActiveRecord::Base
  attr_accessible :body, :image, :involvement, :links, :title, :visible, :video, :href, :slug
  serialize :involvement
  serialize :links

  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

	before_filter :authorize, except: :login

	layout "admin"

  def index
  	@description = "Overview"
  	@pages = Page.order("created_at DESC").all
  	@portfolio = PortfolioItem.order("created_at DESC").all
    @articles = Article.order("created_at DESC").all
  end

	def login
		if request.post?
			session[:username] = params[:username]
			session[:password] = params[:password]
			if admin?
				redirect_to "/admin"
			else
				redirect_to "/login", :notice => "wrong username or password"
			end
		end
	end

	def logout
		reset_session
		redirect_to "/"
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :admin?

  protected

  def authorize
  	unless admin?
  		flash[:error] = "Restricted to admin"
  		redirect_to "/login"
  		false
  	end
  end

  def admin?
  	session[:username] == SENSITIVE["username"] and session[:password] == SENSITIVE["password"]
  end
end

app/controllers/articles_controller.rb
# encoding: utf-8
class ArticlesController < ApplicationController

  before_filter :authorize, except: [:index, :show, :about, :image]

  def index
    @page_title = "All articles"
  end

  def show
  end

  def about
    @page_title = "All articles about #{params[:topic]}"
    @articles = Article.where(topic: params[:topic]).order(:created_at).reverse_order
  end

  def new
    article = Article.new
    render "article_form", layout: "admin"
  end

  def create
    if article.save
      redirect_to article
    else
      render :action => :new
    end
  end

  def edit
    render "article_form", layout: "admin"
  end

  def update
    article.update_attributes(params[:article])
    redirect_to article
  end

  def image
    image = article.images.find_by_name_and_extension(params[:name], params[:extension])
    redirect_to "/article_images/blog-poster.jpg" 
  end

  private

  def article
    article ||= params[:id] ? Article.find(params[:id]) : Article.new(params[:article])
  end
  def articles
    articles = Article.find(:all, order: "created_at DESC")
  end
  helper_method [:article, :articles]
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    
    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to(root_path, :notice => "Message was successfully sent.")
    else
      flash.now.alert = "Please fill all fields."
      render :new
    end
  end

end

app/controllers/pages_controller.rb
# encoding: utf-8
class PagesController < ApplicationController

	before_filter :authorize, except: [:show, :contact, :mail]

	def index
		@pages = Page.all
		page.title = "Einar Löve - Interaction designer"
	end

	def show
		if page.layout == "contact"
			message = Message.new
		end
	end

	def new
		page = Page.new
		render layout: "admin"
	end

	def create
		if page.save
			redirect_to page
		else
			render :action => :new
		end
	end

	def edit
		render layout: "admin"
	end

	def update
		page.update_attributes(params[:page])
		redirect_to page
	end

	def destroy
		page = Page.find(params[:id])
		page.delete
		redirect_to pages_path
	end

	def mail
		@message = Message.new(params[:message])
		if @message.valid?
			ContactMailer.new_message(@message).deliver
			redirect_to("/contact")
			flash[:notice] = "thanks"
		else
			flash[:error] = @message.errors
			flash[:params] = params[:message]
			redirect_to "/contact"
		end
	end

	private

	def page
		page ||= params[:id] ? Page.find(params[:id]) : Page.new(params[:page])
	end
	helper_method :page

end

app/controllers/portfolio_items_controller.rb
class PortfolioItemsController < ApplicationController

	before_filter :authorize, except: :show

	def show
		item = PortfolioItem.find(params[:id])
	end

	def new
		item = PortfolioItem.new
		render "portfolio_form", layout: "admin"
	end

	def create
		if item.save
			redirect_to "/portfolio/#{item.slug}"
		else
			render :action => :new
		end
	end


	def edit
		render "portfolio_form", layout: "admin"
	end

	def update
		throw params[:portfolio_item][:involvement].to_array
		# item.update_attributes(params[:portfolio_item])
		# redirect_to "/portfolio/#{item.slug}"
	end

	private

	def item
		item ||= params[:id] ? PortfolioItem.find(params[:id]) : PortfolioItem.new(params[:portfolio_item])
	end
	helper_method :item

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/_header.haml
- def isNot(controller)
	-	unless params[:controller] == controller or params[:controller] == "admin"
		-return "dimmed"
%hgroup
	.one_column{class: isNot("pages")}
		%h1= link_to "Pages", pages_path
		= link_to "New", new_page_path
		= link_to "View all", pages_path
	.one_column{class: isNot("portfolio_items")}
		%h1= link_to "Portfolio", "/portfolio"
		= link_to "New", new_portfolio_item_path
		= link_to "View all" , "/portfolio"
	.one_column{class: isNot("articles")}
		%h1= link_to "Articles", articles_path
		= link_to "New", new_article_path
		= link_to "View all", articles_path

app/views/admin/index.haml
= render "admin/header"
.one_column
	%ul
		- @pages.each do |page|
			%li
				%h2= link_to page.name, page
				= link_to "Edit", edit_page_path(page)
				= link_to "Delete", "/pages/#{page.name}/delete"
				%p= truncate(page.body, length: 40)
				- unless page.body
					%p= page.description
.one_column
	%ul
		- @portfolio.each do |item|
			%li
				%h2= link_to item.title, portfolio_item_path(item)
				= link_to "Edit", edit_portfolio_item_path(item)
				= link_to "Delete", "/portfolio/#{item.slug}/delete"
				%p= truncate(item.body, length: 40)
.one_column
	%ul
		- @articles.each do |article|
			%li
				%h2= article.title
				= link_to "Edit", edit_article_path(article)
				= link_to "Delete", article_path(article), confirm: "Sure you want to delete #{article.title} ?", method: :delete
				%p= truncate(article.content, length: 40)

app/views/admin/login.haml
.login.one_column
	%h1 Login
	.notice 
		= notice
	%form{action: "login", method: :post}
		%label Username
		%input{name: "username", type: "text"}

		%label Password
		%input{name: "password", type: "password"}
		%input{type: :submit, value: "Login"}

app/views/articles/about.haml
%body.archive
  %header
    %h1 All posts &amp; articles
    %h2
      %a{href:"//einarlove.com/about"}
        about 
        = params[:topic]
  - @articles.each_with_index do |article, index|      
    %article
      %h1= article.title
      %aside
        On 
        %time{pubdate:true, time:article.created_at.strftime("%F")}
          = article.created_at.strftime("%B %eth, %Y")
        about 
        = article.topic

      %p
        - if index == 0 then count = 700 else count = 300 end
        - content = article.content_html.to_s
        - regex = /<figure(.*?)<\/figure>/
        - content = content.gsub(/\n/,"")
        - content = content.gsub(regex," … ")
        - content = strip_tags(content)
        = content.first(count).html_safe + "… "
        %a{href:"/article/#{article.slug}", title:"Read the whole article"} View the whole article

app/views/articles/article_form.haml
= render "admin/header"

= form_for article do |f|
  .one_column
    %div
      = f.label :title, "Title"
      = f.text_field :title 
    %div
      = f.label :author 
      = f.text_field :author
    %div
      = f.label :published
      = f.check_box :published
    %div
      = f.label :topic, "Article topic"
      = f.select(:topic, ["testing", "HTML & CSS", "productivty"])
  .two_columns
    = f.label :content, "Article"
    = f.text_area :content

    = f.submit

app/views/articles/index.haml
%body.archive
  %header
    %h1 All posts &amp; articles
    %h2
      %a{href:"//einarlove.com/about"}
        by Einar Löve
  - articles.each_with_index do |article, index|      
    %article
      %h1= article.title
      %aside
        On 
        %time{pubdate:true, time:article.created_at.strftime("%F")}
          = article.created_at.strftime("%B %eth, %Y")
        about 
        = article.topic

      %p
        - if index == 0 then count = 700 else count = 300 end
        - content = article.content_html.to_s
        - regex = /<figure(.*?)<\/figure>/
        - content = content.gsub(/\n/,"")
        - content = content.gsub(regex," … ")
        - content = strip_tags(content)
        = content.first(count).html_safe + "… "
        %a{href:"/article/#{article.slug}", title:"Read the whole article"} View the whole article

app/views/articles/show.haml
%article.entry
  %header
    %h1= article.title
    %img{src:"/article_images/#{article.id}_poster.jpg"}
  %aside
    %span
      By 
      %adress
        %a{rel:"author", href:"//einarlove.com"}
          = article.author
    %span
      on 
      %time{pubdate:true, datetime:"2012-07-23"}
        = article.created_at.strftime("%B %eth, %Y")
    %span
      about 
      %a{href:"/articles/about/#{article.topic}", title:"View other articles about #{article.topic}"}
        = article.topic
    -#%span
      with 
      %a{href:"#comments", title:"Jump down to comments"}
        4 comments
  %section
    = article.content_html.html_safe
%section.sidebar
  %section#author
    %h2
      %a{href:"#author"}
        About the author
    %p
      My name is Einar Ágúst Löve and I'm an Icelander living and studying Interaction design at Norway's school of creativity in Oslo. This blog is a place for me to express my thoughts about design, programming, and other topics that I find interesting. 
    %p
      My portfolio is on 
      %a{target:"_blank", href:"//einarlove.com"}
        einarlove.com
      and you can contact me on twitter at 
      %a{href:"//twitter.com/einarlove"}
        @einarlove
  %section#articles
    %h2
      %a{href:"#articles"}
        Other articles
    %ul
      - articles.each do |article_item|
        - unless article_item.id == article.id
          %li
            %a{href:"/article/#{article_item.slug}", title:"Read the article '#{article_item.title}' about #{article_item.topic}"}
              = article_item.title
      - if articles.count > 5
        %li
          %a{href:"/articles", title:"View all articles in archive"}
            View all articles
-# %section#comments
  %h2 4 Comments
  %ul
    %li
      %img{src:"assets/avatars/gammel.jpeg", alt:"William Johnson"}
      %a{href:"#"} William Johnson
      %time August the 7th, 2012
      %p
        Great article. My advice would be to check yourself for AD.
    </li>
    %li
      %img{src:"assets/avatars/maria.jpeg", alt:"Maria Zarzonle"}
      %a{href:"#"} Maria Yarzonle
      %time August the 8th, 2012
      %p
        When someone procrastinates, the choice is usually the most time consuming part. They waver between thinking about working on whatever they have to work on and putting it off. Putting off work is only gratifying for that movement or for a short time there after, as eventually it will have to be done. For me this procrastination was with projects, and not just any project, but ones that were due weeks later than they were assigned.
    </li>
    %li
      %img{src:"assets/avatars/kitten.jpeg", alt:"Einar Löve"}
      %a{href:"#"} Einar Löve
      %time August the 8th, 2012
      %p
        Hehe you're right. But big tasks is't always the case. Sometimes the smallests of tasks can be procrastinated.
    </li>
    %li
      %img{src:"assets/avatars/erik.jpeg", alt:"Erik von Gaudalswin"}
      %a{href:"#"} Erik von Gaudalswin
      %time August the 16th, 2012
      %p
        Consider move away from the computer for some time to get a pause. it helps me atleast.

app/views/contact/new.html.erb
<%= form_for @message, :url => contact_path do |form| %>
  <fieldset class="fields">
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    
    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email %>
    </div>
    <div class="field">
      <%= form.label :subject %>
      <%= form.text_field :subject %>
    </div>
    
    <div class="field">
      <%= form.label :body %>
      <%= form.text_area :body %>
    </div>
  </fieldset>
  
  <fieldset class="actions">
    <%= form.submit "Send" %>
  </fieldset>
<% end %>

app/views/layouts/admin.haml
!!! 5
%title= @description
%meta{charset: "utf-8"}
= stylesheet_link_tag "reset", :media => "all"
= stylesheet_link_tag "main", :media => "all"
= csrf_meta_tags
= render "shared/typekit"
- unless request.path == "/login"
	%header
		%hgroup
			%a{ href: "/", title:"Back to frontpage"}
				%h1 Einar Löve
				%h2 Interactiondesigner
		%nav
			= render "shared/navigation"
%section.admin_area
	= yield

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Einarlove</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
		<link href="/assets/oldie.css" rel="stylesheet" type="text/css" />
		<script src="/assets/html5shiv.js" type="text/javascript"></script>
	<![endif]-->
</head>
<body>
	<%= yield %>

<%= render "layouts/analystics" if Rails.env == 'production' %>
</body>
</html>

app/views/layouts/articles.haml
!!! 5
%meta{charset: "utf-8"}
%title= article.title || @page_title
%meta{name:"viewport", content:"width=device-width, target-densityDpi=device-dpi, maximum-scale=1"}
-#= auto_discovery_link_tag :rss, "http://einarlove.com/articles"
%link{rel:"stylesheet", href:"/assets/article-style.css"}
%script{type:"text/javascript", src:"http://use.typekit.com/mec7tyw.js"}
%script{type:"text/javascript"}
  try{Typekit.load();}catch(e){}
= render "shared/analystics" if Rails.env == 'production'

= yield

- if Rails.env == 'development'
  %script
    document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>')

app/views/layouts/pages.haml
!!! 5
%head
	%title= (page.title || page.name)
	%meta{charset: "utf-8"}
	%meta{name: "description", content: "Einar Löve is an interaction designer studying at the Norwegian school of creativity in Oslo. Here you can see some of the projects that he's been involved in."}
	= stylesheet_link_tag "reset", :media => "all"
	= stylesheet_link_tag "main", :media => "all"
	= render "shared/typekit"
	/[if lt IE 9]
		= stylesheet_link_tag "oldie", :media => "all"
		%script{src:"/assets/html5shiv.js", type: "text/javascript"}
%body
	%header
		%hgroup
			%a{ href: "/", title:"Back to frontpage"}
				%h1 Einar Löve
				%h2 Interaction designer
		%nav
			= render "shared/navigation"
	%section{class: page.layout}
		= yield

	%footer
		%div
			%span Copyright 2013
			%a{href:"/admin", title:"Einar Löve", rel: "nofollow"} Einar Löve
		%div
			%span Contact me on twitter
			%a{href:"http://twitter.com/einarlove", title:"Einar Löve", target:"_blank"}
				@einarlove

	= render "shared/analystics" if Rails.env == 'production'

app/views/layouts/portfolio_items.haml
!!! 5
%head
	%title= "#{item.title} — Einar Löve"
	%meta{charset: "utf-8"}
	%meta{name: "description", content: item.body[ 0..155 ] << "..."}
	= stylesheet_link_tag "reset", :media => "all"
	= stylesheet_link_tag "main", :media => "all"
	= render "shared/typekit"
	/[if lt IE 9]
		= stylesheet_link_tag "oldie", :media => "all"
		%script{src:"/assets/html5shiv.js", type: "text/javascript"}
%body
	%header
		%hgroup
			%a{ href: "/", title:"Back to frontpage"}
				%h1 Einar Löve
				%h2 Interaction designer
		%nav
			= render "shared/navigation"
	%section.portfolio_item
		= yield

	%footer
		%div
			%span Copyright 2013
			%a{href:"/admin", title:"Einar Löve"} Einar Löve
		%div
			%span Contact me on twitter
			%a{href:"http://twitter.com/einarlove", title:"Einar Löve", target:"_blank"}
				@einarlove

	= render "shared/analystics" if Rails.env == 'production'

app/views/pages/_contact.haml
%article.two_columns
	%h1= page.title
	.one_column
		= render "contact_form"
	.one_column
		!= simple_format(page.body)

app/views/pages/_contact_form.haml
-if notice == "thanks"
	%b Message sent!
-else
	%form{action: "/contact", method: "post"}
		- errors = flash[:error]
		- if errors.blank?
			%input{type: "hidden", name: "authenticity_token", value: form_authenticity_token}
			%label{for: "message[name]"} Name
			%input{type: "text", name: "message[name]"}
			%label{for: "message[email]"} Email
			%input{type: "text", name: "message[email]"}
			%label{for: "message[body]"} Message
			%textarea{name: "message[body]"}
			%input{type: "submit", value: "Send message"}
		- else
			- input = flash[:params]
			%input{type: "hidden", name: "authenticity_token", value: form_authenticity_token}
			%label{for: "message[name]"} Name
			%span.error= errors[:name][0]
			%input{type: "text", name: "message[name]", value: input[:name]}
			%label{for: "message[email]"} Email
			%span.error= errors[:email][0]
			%input{type: "text", name: "message[email]", value: input[:email]}
			%label{for: "message[body]"} Message
			%span.error= errors[:body][0]
			%textarea{name: "message[body]"}
				= input[:body]
			%input{type: "submit", value: "Send message"}

app/views/pages/_page_form.haml
= render "admin/header"


= form_for page do |f|
	.one_column
		= f.label :name 
		= f.text_field :name 

		= f.label :title 
		= f.text_field :title 

		= f.label :description, "Short description" 
		= f.text_field :description 

		= f.label :visible, "Visible in menu"
		= f.check_box :visible

		= f.label :layout, "Page layout"
		= f.select(:layout, ["portfolio", "static", "blog", "contact"])

	.one_column
		= f.label :body
		= f.text_area :body

	.one_column
		= f.label :image 
		= f.file_field :image 


		= f.submit

app/views/pages/_portfolio.haml
%ul.portfolio_items
	- PortfolioItem.order("created_at DESC").limit(6).where(visible: true).each do |item|
		- if current_page?("/portfolio/"+item.slug)
			- current_item = "current_item"
		%li
			%a{ href: "/portfolio/#{item.slug}", class: current_item}
				%img{src: "/portfolio/images/"+item.slug+"_thumb.jpg"}

app/views/pages/_static.haml
%article.one_column
	%h1= page.title
	!= simple_format(page.body)
- if page.image
	%img.two_columns{src: image_path("me.jpg")}

app/views/pages/edit.haml
= render "page_form"

app/views/pages/index.haml
%h1 Page sitemap
%table
	%th name
	%th title
	%th layout
	%th description
	%th visible
	%th image
	%th body
	%th slug
	- @pages.each do |page|
		%tr
			%td= page.name
			%td= page.title
			%td= page.layout
			%td= page.description
			%td= page.visible
			%td= page.image
			%td= truncate(page.body, :length => 30)
			%td= page.slug
			%td= button_to "Edit", edit_page_path(page), method: :get
			%td= button_to "Delete", page, :method => :delete

=link_to "Create new page", new_page_path

app/views/pages/new.haml
= form_for @page do |f|

	= f.label :name 
	= f.text_field :name 

	= f.label :title 
	= f.text_field :title 

	= f.label :layout 
	= f.text_field :layout 

	= f.label :description 
	= f.text_field :description 

	= f.label :image 
	= f.file_field :image 

	= f.label :body
	= f.text_area :body

	= f.submit

app/views/pages/show.haml
= render page.layout

app/views/portfolio_items/portfolio_form.haml
= render "admin/header"

= form_for item do |f|
  .one_column
    %div
      = f.label :title, "Title"
      = f.text_field :title
    %div
      = f.label :visible
      = f.check_box :visible

      = f.label :video
      = f.check_box :video
    %div
      = f.label :involvement
      = f.text_field :involvement
    / %div
    /   = f.label :links
    /   = f.text_field :links
  .two_columns
    = f.label :body, "Description"
    = f.text_area :body

    = f.submit



  / :body, :image, :involvement, :links, :title, :visible, :video, :slug

app/views/portfolio_items/show.haml
%article.one_column
	%h1= item.title
	!= simple_format(item.body)
	- if item.involvement
		%h2 Work
		- item.involvement.each do |w|
			%li= w

	- if item.links
		%h2 Links
		- item.links.each do |link|
			%li
				%a{href: link[1], target: "_blank"}= link[0]
- if item.video == "t"
	.video_container.two_columns
		%video{poster: "/portfolio/images/"+item.slug+".jpg"}
			%source{src: "/portfolio/videos/"+item.slug+".mp4", type: 'video/mp4; codecs: "avc1.42E01E, mp4a.40.2"', autobuffer: true}
			%source{src: "/portfolio/videos/"+item.slug+".webm", type: 'video/webm; codecs="vp8, vorbis"', autobuffer: true}
			= javascript_include_tag "video_controller"
			%p
				Your browser does not have video support. Upgrade your browser
				%a{href:"http://www.updateyourbrowser.net/en/", target:"_blank"} here.
		.video_controller
		.progress_bar
			.time_bar

- elsif item.image
	%a.two_columns{href: item.href}
		%img{src: "/portfolio/images/"+item.slug+".jpg"}

= render "pages/portfolio"

app/views/shared/_analystics.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-26995819-1']);
  _gaq.push(['_setDomainName', 'einarlove.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/shared/_navigation.haml
%ul
	-if admin?
		- if params[:controller] == "admin" or ["new", "edit"].include? params[:action]
			- admin_current = "current_page"
		%li
			%a{href:"/admin", title:"Admin area", class: admin_current} Admin	
	- Page.where("visible = ?", true).order("created_at DESC").each do |page|
		- if params[:id] == page.name or params[:controller] == page.name and params[:action] == "show"
			- current_page = "current_page"
		%li
			%a{href:"/"+page.slug, title:page.description, class: current_page}= page.name

app/views/shared/_typekit.haml
-# ori0nli for Development and fgo2xid for Production
- if Rails.env == 'production'
	%script{type:"text/javascript", src:"http://use.typekit.com/fgo2xid.js"}
- else
	%script{type:"text/javascript", src:"http://use.typekit.com/ori0nli.js"}
%script{type:"text/javascript"}
	try{Typekit.load();}catch(e){}